#!/usr/bin/env bash
# Copyright 2026 Scout Project Contributors
# Licensed under the Apache License, Version 2.0
#
# Full Pop!_OS peer bring-up:
#   1) wireguard-tools
#   2) optional Ollama + scout-dev + scout-dev1.0.1 (gate model)
#   3) mesh enroll + split-tunnel scoutwg0
#   4) write local wiring env for stack/gate tooling
#
# Required env (from hub operator — not baked into the tarball):
#   SCOUT_MESH_ENROLL_URL   e.g. http://192.168.1.154:18080
#   SCOUT_MESH_ENTRY_TOKEN  mesh entry token (NOT the Windows admin token)
#
# Optional:
#   SCOUT_MESH_ENDPOINT_OVERRIDE=192.168.1.154:51820   # when public hairpin fails
#   SCOUT_INSTALL_OLLAMA=1|0                          # default 1 if ollama missing
#   SCOUT_BUILD_GATE_MODEL=1|0                        # default 1
#   SKIP_MESH_JOIN=1                                  # only install tools/models
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# suite root may be peer_setup/ alone or nested under extracted bundle
BUNDLE_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
if [[ -d "$SCRIPT_DIR/llm" ]]; then
  BUNDLE_ROOT="$SCRIPT_DIR"
elif [[ -d "$BUNDLE_ROOT/llm" ]]; then
  :
elif [[ -d "$SCRIPT_DIR/../llm" ]]; then
  BUNDLE_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
fi

cd "$SCRIPT_DIR"

echo "=============================================="
echo " Scout Mesh Pop!_OS peer install_all"
echo " bundle_root=$BUNDLE_ROOT"
echo "=============================================="

./bootstrap_peer.sh

# --- Ollama + gate model ---------------------------------------------------
BUILD_GATE="${SCOUT_BUILD_GATE_MODEL:-1}"
INSTALL_OLLAMA="${SCOUT_INSTALL_OLLAMA:-1}"

if [[ "$BUILD_GATE" == "1" ]]; then
  if ! command -v ollama >/dev/null 2>&1; then
    if [[ "$INSTALL_OLLAMA" == "1" ]]; then
      echo "[*] installing Ollama (official script)..."
      curl -fsSL https://ollama.com/install.sh | sh
    else
      echo "[!] ollama missing and SCOUT_INSTALL_OLLAMA=0 — skipping gate model"
      BUILD_GATE=0
    fi
  fi
fi

if [[ "$BUILD_GATE" == "1" ]]; then
  # ensure daemon
  if ! curl -fsS --max-time 2 http://127.0.0.1:11434/api/tags >/dev/null 2>&1; then
    echo "[*] starting ollama serve in background..."
    nohup ollama serve >/tmp/ollama-peer-serve.log 2>&1 &
    for _ in $(seq 1 30); do
      curl -fsS --max-time 1 http://127.0.0.1:11434/api/tags >/dev/null 2>&1 && break
      sleep 1
    done
  fi
  if ! curl -fsS --max-time 2 http://127.0.0.1:11434/api/tags >/dev/null 2>&1; then
    echo "[x] ollama API not reachable on :11434" >&2
    exit 1
  fi

  MODEL_DIR="$BUNDLE_ROOT/llm/dev"
  if [[ ! -f "$MODEL_DIR/Modelfile.scout-dev1.0.1" ]]; then
    echo "[x] missing $MODEL_DIR/Modelfile.scout-dev1.0.1 in bundle" >&2
    exit 1
  fi

  echo "[*] ensuring base qwen3:8b..."
  ollama pull qwen3:8b

  # scout-dev1.0.1 FROM scout-dev FROM scout-core1.0.5 — create chain if present in bundle
  if [[ -f "$BUNDLE_ROOT/llm/core/Modelfile.scout-core1.0.5" ]]; then
    echo "[*] building scout-core1.0.5..."
    ollama create scout-core1.0.5 -f "$BUNDLE_ROOT/llm/core/Modelfile.scout-core1.0.5"
  fi
  echo "[*] building scout-dev..."
  ollama create scout-dev -f "$MODEL_DIR/Modelfile.scout-dev"
  echo "[*] building scout-dev1.0.1 (unauth gate specialist)..."
  ollama create scout-dev1.0.1 -f "$MODEL_DIR/Modelfile.scout-dev1.0.1"
  ollama list | grep -E 'scout-dev' || true
  echo "[+] gate model ready: scout-dev1.0.1"
fi

# --- local wiring env ------------------------------------------------------
STATE_DIR="${SCOUT_MESH_STATE_DIR:-$SCRIPT_DIR/state}"
mkdir -p "$STATE_DIR"
chmod 700 "$STATE_DIR"
WIRING="$STATE_DIR/peer_wiring.env"
cat > "$WIRING" <<EOF
# Generated by install_all.sh — local peer wiring (no secrets required here)
SCOUT_MESH_IFACE=${SCOUT_MESH_IFACE:-scoutwg0}
SCOUT_MESH_CIDR=10.66.0.0/16
SCOUT_MESH_HUB_ADDRESS=10.66.0.1
SCOUT_NETWORK_ADVERTISE_HOST=10.66.0.1
SCOUT_GATE_MODEL=scout-dev1.0.1
OLLAMA_MODEL_DEV=ollama/scout-dev
OLLAMA_MODEL_DEV_GATE=ollama/scout-dev1.0.1
BACKEND_PULL_ALLOW_CIDRS=10.66.0.0/16,127.0.0.1/32,::1/128,172.16.0.0/12,192.168.0.0/16,10.0.0.0/8
# Mesh join secrets come from the operator environment, not this file:
#   SCOUT_MESH_ENROLL_URL  SCOUT_MESH_ENTRY_TOKEN  SCOUT_MESH_ENDPOINT_OVERRIDE
EOF
chmod 644 "$WIRING"
echo "[+] wrote $WIRING"

# copy client helpers if present
if [[ -d "$BUNDLE_ROOT/llm/client" ]]; then
  mkdir -p "$STATE_DIR/llm-client"
  cp -a "$BUNDLE_ROOT/llm/client/." "$STATE_DIR/llm-client/"
  echo "[+] llm client copied to $STATE_DIR/llm-client"
fi

# --- mesh join -------------------------------------------------------------
if [[ "${SKIP_MESH_JOIN:-0}" == "1" ]]; then
  echo "[*] SKIP_MESH_JOIN=1 — done after tools/models/wiring"
  exit 0
fi

if [[ -z "${SCOUT_MESH_ENROLL_URL:-}" || -z "${SCOUT_MESH_ENTRY_TOKEN:-}" ]]; then
  cat <<EOF
[!] Mesh join skipped — set secrets then re-run join only:

  export SCOUT_MESH_ENROLL_URL="http://HUB_LAN_OR_DNS:18080"
  export SCOUT_MESH_ENTRY_TOKEN="…"          # mesh entry token from hub
  # optional when public endpoint hairpins badly:
  # export SCOUT_MESH_ENDPOINT_OVERRIDE="HUB_LAN:51820"
  ./join_mesh.sh && ./verify_peer.sh

Tools/models/wiring are installed. Mesh join needs the operator entry token.
EOF
  exit 0
fi

./join_mesh.sh
./verify_peer.sh || {
  echo "[!] verify failed — try SCOUT_MESH_ENDPOINT_OVERRIDE=HUB_LAN_IP:51820 and re-run ./join_mesh.sh" >&2
  exit 1
}

echo ""
echo "[+] Pop!_OS peer install_all complete"
echo "    mesh:   scoutwg0 → 10.66.0.1"
echo "    model:  scout-dev1.0.1 (gate)"
echo "    wiring: $WIRING"
echo "    gate CLI: python3 $STATE_DIR/llm-client/llm_set_client.py gate --task GATE 'Event: ...'"
