#!/usr/bin/env bash
# Copyright 2026 Scout Project Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Join a Debian trixie box to the Scout Mesh (WireGuard, scoutwg0).
#
# The Scout Mesh is a SPLIT tunnel: only 10.66.0.0/16 is routed through the
# tunnel. The host keeps its normal LAN/Internet default route, so git, Kepler,
# warp.dev etc. keep working while on the mesh. Do NOT set AllowedIPs=0.0.0.0/0
# on this tunnel unless you deliberately want a full tunnel.
#
# After 'up', this script verifies the host still has an IPv4 default route.
# That check exists because a missing IPv4 default (IPv6-RA-only LAN, no DHCPv4
# gateway) reproduces exactly: DNS resolves, then "rtnetlink: network is
# unreachable" for git/Hub, while browsers/email still work over IPv6.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
source "$SCRIPT_DIR/lib.sh"

SUDO=""
if ((EUID != 0)); then
  require_cmd sudo
  SUDO="sudo"
fi

# --- tunables (all env-overridable) ------------------------------------------
HUB_IP="${SCOUT_MESH_HUB_ADDRESS:-10.66.2.3}"          # map hub + blackboard host
OWN_IP="${SCOUT_MESH_OWN_IP:-10.66.2.5}"               # this box's scoutwg0 address
HUB_PUBKEY="${SCOUT_MESH_HUB_PUBKEY:-}"                # hub wireguard public key
HUB_ENDPOINT="${SCOUT_MESH_HUB_ENDPOINT:-}"            # hub WG endpoint (host:port)
WG_CONF_DIR="${WG_CONF_DIR:-/etc/wireguard}"
WG_IFACE="scoutwg0"
WG_LISTEN_PORT="51821"
MTU="1420"
ALLOWED_IPS="10.66.0.0/16"

usage() {
  cat <<EOF
Usage: $(basename "$0") [up|down|status] [options]

Commands:
  up        generate keys if needed, render $WG_CONF_DIR/$WG_IFACE.conf,
            enable wg-quick@$WG_IFACE, and verify the mesh + default route (default)
  down      stop wg-quick@$WG_IFACE (does not remove the config/keys)
  status    show wg show + this host's mesh IP

Env (all optional):
  SCOUT_MESH_HUB_ADDRESS     hub mesh IP            (default: $HUB_IP)
  SCOUT_MESH_OWN_IP          this box's mesh IP     (default: $OWN_IP)
  SCOUT_MESH_HUB_PUBKEY      hub WireGuard pubkey  (required for up)
  SCOUT_MESH_HUB_ENDPOINT    hub endpoint host:port (required for up)
  SCOUT_MESH_ALLOWED_IPS     split-tunnel CIDRs     (default: $ALLOWED_IPS)

To also reach another peer's Ollama over the mesh, add a second [Peer] block for
that peer with AllowedIPs = <peer-mesh-ip>/32.

Run AFTER ./bootstrap_agent_box.sh (installs wireguard-tools).
EOF
}

gen_keys() {
  local priv="$WG_CONF_DIR/${WG_IFACE}.key"
  if [[ -f "$priv" ]]; then
    ok "Existing key present: $priv (keeping it)"
  else
    info "Generating WireGuard keys -> $priv"
    ${SUDO} install -m 600 /dev/null "$priv"
    ${SUDO} bash -c "wg genkey > '$priv'"
    ${SUDO} chmod 600 "$priv"
  fi
  WG_PRIVKEY="$(${SUDO} cat "$priv")"
  WG_PUBKEY="$(printf '%s' "$WG_PRIVKEY" | ${SUDO} tee /dev/null >/dev/null; printf '%s' "$WG_PRIVKEY" | wg pubkey)"
}

confirm_hub() {
  if [[ -z "$HUB_PUBKEY" ]]; then
    fail "SCOUT_MESH_HUB_PUBKEY is required (ask the hub operator for its 'wg show scoutwg0 public-key'). See --help."
  fi
  if [[ -z "$HUB_ENDPOINT" ]]; then
    fail "SCOUT_MESH_HUB_ENDPOINT is required (hub host:port, e.g. 100.78.191.61:51820). See --help."
  fi
}

render_conf() {
  info "Rendering $WG_CONF_DIR/$WG_IFACE.conf (split tunnel: $ALLOWED_IPS)"
  ${SUDO} tee "$WG_CONF_DIR/$WG_IFACE.conf" >/dev/null <<EOF
# Scout Mesh (WireGuard) - generated by agent_box_setup_trixie/configure_scout_mesh.sh
# SPLIT tunnel: only $ALLOWED_IPS routes through the tunnel.
[Interface]
Address = $OWN_IP/32
PrivateKey = $WG_PRIVKEY
ListenPort = $WG_LISTEN_PORT
MTU = $MTU

[Peer]
PublicKey = $HUB_PUBKEY
Endpoint = $HUB_ENDPOINT
AllowedIPs = $ALLOWED_IPS
PersistentKeepalive = 25
EOF
}

start_mesh() {
  require_cmd wg wg-quick
  confirm_hub
  gen_keys
  render_conf
  info "Starting wg-quick@$WG_IFACE (persistent via systemd)..."
  ${SUDO} systemctl enable wg-quick@"$WG_IFACE" >/dev/null 2>&1 || true
  if systemctl is-active --quiet wg-quick@"$WG_IFACE"; then
    ok "wg-quick@$WG_IFACE already active"
  else
    ${SUDO} systemctl start wg-quick@"$WG_IFACE"
  fi

  info "Verifying mesh connectivity to hub $HUB_IP..."
  if ping -c 1 -W 2 "$HUB_IP" >/dev/null 2>&1; then
    ok "Mesh ping $HUB_IP OK"
  else
    warn "Hub $HUB_IP did not answer ping within 2s (hub may block ICMP); continuing."
  fi
  if curl -fsS --connect-timeout 3 "http://$HUB_IP:8765/health" >/dev/null 2>&1; then
    ok "Hub blackboard reachable at http://$HUB_IP:8765/health"
  else
    warn "Hub blackboard health did not respond yet; it may not be installed on the hub."
  fi

  echo ""
  info "Default-route (Internet) integrity check..."
  if ! mesh_verify_default_ipv4_route; then
    exit 1
  fi
  ok "IPv4 default route still intact; Internet over LAN while mesh is up."
  if ip route get 1.1.1.1 >/dev/null 2>&1; then
    ok "Inline check: ip route get 1.1.1.1 -> $(ip route get 1.1.1.1 | awk '{print $3; exit}' 2>/dev/null || echo ok)"
  fi

  echo ""
  ok "Scout Mesh is UP:"
  ok "  This box:  $OWN_IP/32 on $WG_IFACE"
  ok "  Hub:       $HUB_IP (map :18080, blackboard :8765)"
  ok "  Split:     $ALLOWED_IPS via tunnel; Internet via LAN default route"
  info "Share this box's public key with peers that should reach it:"
  echo "  ${C_INFO}${WG_PUBKEY}${C_RESET}"
}

stop_mesh() {
  if systemctl is-active --quiet wg-quick@"$WG_IFACE"; then
    ${SUDO} systemctl stop wg-quick@"$WG_IFACE"
    ok "Stopped wg-quick@$WG_IFACE"
  else
    ok "wg-quick@$WG_IFACE already inactive"
  fi
}

mesh_status() {
  if command -v wg >/dev/null 2>&1; then
    ${SUDO} wg show
  else
    warn "wg not installed; run ./bootstrap_agent_box.sh"
  fi
}

CMD="${1:-up}"
case "$CMD" in
  up)     start_mesh ;;
  down)   stop_mesh ;;
  status) mesh_status ;;
  -h|--help) usage ;;
  *) fail "unknown command: $CMD (up|down|status, see --help)" ;;
esac

echo ""
ok "Mesh command complete."