#!/usr/bin/env bash
# Copyright 2026 Scout Project Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Install the scout_crew package on a headless Debian trixie agent box and
# enroll this box with the hub blackboard. Pure CLI: no PySide6 GUI is
# installed (the crew runs via the 'scout' / 'scout_crew' CLI and systemd).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
source "$SCRIPT_DIR/lib.sh"

SUDO=""
if ((EUID != 0)); then
  require_cmd sudo
  SUDO="sudo"
fi

SCOUT_CREW_ROOT="${SCOUT_CREW_ROOT:-$HOME/scout_crew}"
VENV_DIR="${SCOUT_VENV_DIR:-$HOME/.scout/venv}"
SCOUT_CREW_GIT_URL="${SCOUT_CREW_GIT_URL:-https://github.com/scout-hazard-system/scout_crew.git}"
HUB_IP="${SCOUT_MESH_HUB_ADDRESS:-10.66.2.3}"
BB_PORT="8765"
DEVICE_ID="${SCOUT_BB_DEVICE:-$(hostname)}"
ROLE="${SCOUT_BB_ROLE:-alert}"
ENROLL=1
ENTRY_TOKEN="${SCOUT_BLACKBOARD_ENTRY_TOKEN:-}"

usage() {
  cat <<EOF
Usage: $(basename "$0") [options]

Options:
  --no-enroll      do not mint a blackboard device token against the hub
  --device <id>    device identifier for the blackboard token (default: hostname)
  --help           show this help

Env:
  SCOUT_CREW_ROOT            scout_crew checkout (default: $SCOUT_CREW_ROOT)
  SCOUT_VENV_DIR             dedicated venv for the crew (default: $VENV_DIR)
  SCOUT_CREW_GIT_URL         clone source if checkout missing
  SCOUT_MESH_HUB_ADDRESS     hub mesh IP (default: $HUB_IP)
  SCOUT_BB_DEVICE / SCOUT_BB_ROLE
  SCOUT_BLACKBOARD_ENTRY_TOKEN   hub entry token for key authorization
                                   (otherwise the token must be issued hub-side)
EOF
}

ARGS=("$@")
i=0
while ((i < ${#ARGS[@]})); do
  case "${ARGS[$i]}" in
    --no-enroll) ENROLL=0; i=$((i + 1)) ;;
    --device=*)  DEVICE_ID="${ARGS[$i]#*=}"; i=$((i + 1)) ;;
    --device)    DEVICE_ID="${ARGS[$((i + 1))]:-}"; i=$((i + 2)) ;;
    -h|--help)   usage; exit 0 ;;
    *) fail "unknown argument: ${ARGS[$i]} (see --help)" ;;
  esac
done

require_cmd git curl python3

# --- 1. checkout + venv ------------------------------------------------------
if [[ -d "$SCOUT_CREW_ROOT/.git" ]]; then
  ok "scout_crew checkout present at $SCOUT_CREW_ROOT"
else
  info "Cloning scout_crew -> $SCOUT_CREW_ROOT"
  git clone --depth 1 "$SCOUT_CREW_GIT_URL" "$SCOUT_CREW_ROOT"
fi
[[ -f "$SCOUT_CREW_ROOT/src/scout_crew/crew.py" ]] \
  || fail "scout_crew source not found at $SCOUT_CREW_ROOT (inner src/scout_crew missing)"

if [[ -x "$VENV_DIR/bin/python" ]]; then
  ok "Crew venv present at $VENV_DIR"
else
  info "Creating crew venv at $VENV_DIR"
  python3 -m venv "$VENV_DIR"
fi
CREW_PY="$VENV_DIR/bin/python"

info "Installing scout_crew (editable) + crewai into the crew venv..."
"$CREW_PY" -m pip install --upgrade pip >/dev/null
"$CREW_PY" -m pip install -e "$SCOUT_CREW_ROOT"

# Blackboard venv (pure stdlib, small) reuses the same interpreter.
info "Writing stack env so the crew finds the mesh hub + blackboard..."
ENV_FILE="$HOME/.config/scout/scout_mesh.env"
mkdir -p "$(dirname "$ENV_FILE")"
cat > "$ENV_FILE" <<EOF
# Scout Mesh runtime env for the agent box (generated by install_crew_headless.sh)
export SCOUT_MESH_HUB_ADDRESS=$HUB_IP
export SCOUT_BLACKBOARD_URL=http://$HUB_IP:$BB_PORT
export SCOUT_BB_DEVICE=$DEVICE_ID
export SCOUT_BB_ROLE=$ROLE
export OLLAMA_BASE_URL=http://127.0.0.1:11434
# Block any accidental cloud-LLM use while running local/mesh-only:
export CREWAI_TUNNEL=false
EOF
chmod 600 "$ENV_FILE"
ok "Stack env -> $ENV_FILE"

# --- 2. blackboard enrollment (key authorization against the hub) ------------
if ((ENROLL)); then
  if [[ -z "$ENTRY_TOKEN" ]]; then
    warn "SCOUT_BLACKBOARD_ENTRY_TOKEN unset - skipping on-box enrollment."
    warn "Ask the hub operator to run on the hub:"
    warn "  map_server_setup/setup_blackboard.sh --device $DEVICE_ID --device-role $ROLE"
    warn "then set SCOUT_BLACKBOARD_TOKEN from the returned \$HOME/.scout/blackboard/tokens/$DEVICE_ID.token"
  else
    info "Enrolling device '$DEVICE_ID' (role=$ROLE) with hub blackboard at $HUB_IP..."
    (
      export PYTHONPATH="$SCOUT_CREW_ROOT/src"
      export SCOUT_BLACKBOARD_URL="http://$HUB_IP:$BB_PORT"
      export SCOUT_BB_DEVICE="$DEVICE_ID"
      export SCOUT_BB_ROLE="$ROLE"
      export SCOUT_BLACKBOARD_ENTRY_TOKEN="$ENTRY_TOKEN"
      "$VENV_DIR/bin/python" - <<PY
import json, os
from pathlib import Path
from scout_crew.blackboard.client import BlackboardClient
dev = os.environ["SCOUT_BB_DEVICE"]
r = BlackboardClient(base_url=os.environ["SCOUT_BLACKBOARD_URL"]).authorize(
    device_id=dev, role=os.environ["SCOUT_BB_ROLE"],
    categories=["pipeline"], ttl=60 * 60 * 24 * 30,
    entry_token=os.environ["SCOUT_BLACKBOARD_ENTRY_TOKEN"])
out_dir = Path.home() / ".scout" / "blackboard"
out_dir.mkdir(parents=True, exist_ok=True)
(out_dir / "devices" / f"{dev}.json").write_text(json.dumps(r, indent=2) + "\n")
(out_dir / "tokens" / f"{dev}.token").write_text(r["token"] + "\n")
print(f"enrolled {dev}: role={r.get('role')}, observed_ip={r.get('observed_ip')}, expires_in={r.get('expires_in')}")
print(f"token file: {out_dir / 'tokens' / f'{dev}.token'}")
PY
    )
    TOK_FILE="$HOME/.scout/blackboard/tokens/$DEVICE_ID.token"
    if [[ -s "$TOK_FILE" ]]; then
      printf 'export SCOUT_BLACKBOARD_TOKEN=%s\n' "$(cat "$TOK_FILE")" >> "$ENV_FILE"
      chmod 600 "$ENV_FILE"
      ok "Blackboard token saved to $ENV_FILE (SCOUT_BLACKBOARD_TOKEN)"
    else
      warn "Enrollment did not produce a token file; continue manually (see above)."
    fi
  fi
fi

echo ""
ok "Crew install complete."
cat <<EOF
Next:
  1. source $ENV_FILE (add to ~/.bashrc / ~/.profile)
  2. $VENV_DIR/bin/scout status          # model roster + mesh/hub probes
  3. $VENV_DIR/bin/scout crew --help     # run the crew headless
  4. ./install_services.sh && ./verify_agent_box.sh
EOF